motor_info: # TODO: update
        min_pwm: 0.6 # 1200 [ms]
        max_pwm: 0.96 # 1920 [ms]
        min_thrust: 0 #  [N]
        force_landing_thrust: 6.5 #[N]
        m_f_rate: -0.006
        pwm_conversion_mode: 0 # SQRT Mode
        vel_ref_num: 1
        ref1:
                voltage: 50
                max_thrust: 15 # N
                polynominal2: 0.01556302 # 0.07983707 # x10
                polynominal1: -1.66712308 # -6.627443098 # x10
                polynominal0: 4.455046 # 12.3593793002 # x1

        speed_rate: 10.0
