aerial_robot_control_name: aerial_robot_control/fully_actuated_nobend_controller

controller:
  control_method : 0
  xy:
    p_gain: 10
    i_gain: 0.3
    d_gain: 1.5
    limit_sum: 3
    limit_p: 3
    limit_i: 1.5
    limit_d: 3

  z:
    p_gain: 5.0
    i_gain: 2.5
    d_gain: 5.0
    limit_err_p: 1.0
    limit_sum: 1000 # N for clamping thrust force
    limit_p: 200 # m / s^2
    limit_i: 400 # m / s^2
    limit_d: 200 # m / s^2
    landing_err_z: -0.2
    force_landing_descending_rate: -0.6

  roll:
    p_gain: 15
    i_gain: 0.3
    d_gain: 5 # 5: good, 7: deverge in the takeoff phase
    limit_sum: 10
    limit_p: 10
    limit_i: 10
    limit_d: 10
  
  pitch:
    p_gain: 15
    i_gain: 3
    d_gain: 5 # 5: good, 7: deverge in the takeoff phase
    limit_sum: 10
    limit_p: 10
    limit_i: 10
    limit_d: 10
  yaw:
    p_gain: 15
    i_gain: 1
    d_gain: 2
    limit_sum: 20.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 12.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: true

  pitch_2:
    p_gain: 15
    i_gain: 3
    d_gain: 5 # 5: good, 7: deverge in the takeoff phase
    limit_sum: 10
    limit_p: 10
    limit_i: 10
    limit_d: 10
  yaw_2:
    p_gain: 15
    i_gain: 1
    d_gain: 2
    limit_sum: 20.0 # N for clamping thrust force
    limit_p: 4.0
    limit_i: 12.0
    limit_d: 4.0
    limit_err_p: 0.4
    need_d_control: true
  
  pitch_pcs_gain: 1
  yaw_pcs_gain: 1